
name: Kotlin CI

on:
  push:
    branches: [ master ]  # only runs when you push to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build the project
        run: ./gradlew build
